name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout esp32_mass repo
      uses: actions/checkout@v2
    - name: Checkout fakufaku/esp32-fft
      uses: actions/checkout@v2.3.2
      with:
        repository: fakufaku/esp32-fft
        path: components/esp32-fft
    - name: Upload build artiface
      uses: actions/upload-artifact@v2
      with:
        name: preBuild
        path: .
    - name: ESP32-RTOS-SDK (IDF Style) Build
      uses: sebastianPsm/esp32-ci-env-action@1
