name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout esp32_mass repo
      uses: actions/checkout@v2
    - name: Checkout fakufaku/esp32-fft
      uses: actions/checkout@v2.3.2
      with:
        repository: fakufaku/esp32-fft
        path: esp32_mass/components
    - name: ESP8266-RTOS-SDK (IDF Style) Build
      uses: nsfilho/esp8266-rtos-sdk@v2
      with:
        # Arguments to pass for make
        makearg: # optional, default is defconfig all size-components
